version: '2.4'
services:
  netlink-api:
    build: .
    network_mode: host
    cap_drop:
      - ALL
    cap_add: 
      - NET_ADMIN
    environment:
      LISTEN: ":4821"
    ports:
      - "4821:4821"
